version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  build:
    commands:
      # build lambda code
      - yarn build
      - yarn install --production --modules-folder ./dist/node_modules
<<<<<<< HEAD

      # package lambda (creates a zip file with the source code)
=======
      # package lambda
>>>>>>> feature/add_deployment
      - >
        aws cloudformation package
        --template cloudformation/deploy-master.yml
        --s3-bucket $S3_BUCKET
        --s3-prefix $S3_PREFIX
        --output-template cloudformation/deploy-master-packaged.yml
        --region $AWS_REGION
<<<<<<< HEAD

      # sync deployment templates to S3
      - >
        aws s3 cp
        cloudformation/
        s3://$S3_BUCKET/$S3_PREFIX
        --exclude "*"
        --include "deploy-*.yml"

      # sync compiled deployment template
      - >
        aws s3 cp
        cloudformation/deploy-master-packaged.yml
        s3://$S3_BUCKET/$S3_PREFIX/deploy-master-packaged.yml
      
      # create build output file
      - printf '{"ArtifactsLocation":"%s"}' $S3_PREFIX > build.json
=======
      # sync deployment templates
      - >
        aws s3 sync
        cloudformation/
        s3://$S3_BUCKET/$S3_PREFIX/
        --exclude "*"
        --include "deploy-*.yml"
      - >
        aws s3 cp
        cloudformation/deploy-master-packaged.yml
        s3://${S3_BUCKET}/${S3_PREFIX}/deploy-master-packaged.yml
      
      # output ArtifactsLocation in a build.json file
      - printf '{"ArtifactsLocation":"%s"}' ${S3_PREFIX} > build.json
>>>>>>> feature/add_deployment

artifacts:
  files:
    - cloudformation/deploy-master-packaged.yml
    - build.json
  discard-paths: yes
