version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  build:
    commands:
      # build lambda code
      - yarn build
      - yarn install --production --modules-folder ./dist/node_modules
